name: Hello DP Workflow
on: workflow_dispatch
env:
  name: 'DP Singh'
jobs:
  my_first_job:
    name: My first job
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Greetings
        run: echo "Hello from ubuntu create by $name"

  my_second_job:
    name: My second job
    needs: my_first_job
    if: always()
    runs-on: windows-latest
    steps:
      - name: Greetings
        run: write-host "Hello from windows created by $env:name"

