name: Hello DP Workflow

on: workflow_dispatch

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Greetings
        run: echo "Hello from ubuntu"

  my_second_job:
    name: My second job
    needs: my_first_job
    runs-on: windows-latest
    steps:
      - name: Greetings
        run: write-host "Hello from windows"

