name: Hello DP Workflow
on: workflow_dispatch
jobs:
  my_first_job:
    name: My first job
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      name: 'DP Singh'
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Greetings
        run: echo "Hello from ubuntu create by $name"

  my_second_job:
    name: My second job
    needs: my_first_job
    if: always()
    runs-on: windows-latest
    steps:
      - name: Greetings
        run: write-host "Hello from windows created by $name"

